# Generated by Django 3.0.1 on 2020-01-03 23:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('characterClass', models.CharField(choices=[('WAR', 'Warrior'), ('WIZ', 'Wizzard')], default='WAR', max_length=3)),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hpMax', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hp', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('strength', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('physicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('minHpMax', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(10)])),
                ('minStrength', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('minAgility', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('minInt', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('minPhysResis', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('minMagRes', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=40)),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hpMax', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('physicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chestCharacterClass', to='app.CharacterClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=40)),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hp', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=40)),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hpMax', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('physicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headCharacterClass', to='app.CharacterClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chestInventory', to='app.Chest')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=40)),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hpMax', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('physicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('oneHanded', models.BooleanField(default=True)),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weaponCharacterClass', to='app.CharacterClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='New Item', max_length=40)),
                ('strength', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('hpMax', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('physicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magicalResistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('characterClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legCharacterClass', to='app.CharacterClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InventoryConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Consumable')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='consumables',
            field=models.ManyToManyField(through='app.InventoryConsumable', to='app.Consumable'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headInventory', to='app.Head'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='leg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legInventory', to='app.Leg'),
        ),
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='app.Inventory'),
        ),
    ]
