# Generated by Django 3.0.1 on 2019-12-20 10:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('level', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('hpMax', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('hp', models.PositiveIntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('armor', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('physicalResistance', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
                ('magicalResistance', models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Chest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('level', models.IntegerField()),
                ('hpMax', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('physicalResistance', models.IntegerField()),
                ('magicalResistance', models.IntegerField()),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('oneHanded', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Consumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('level', models.IntegerField()),
                ('hpMax', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('physicalResistance', models.IntegerField()),
                ('magicalResistance', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('level', models.IntegerField()),
                ('hpMax', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('physicalResistance', models.IntegerField()),
                ('magicalResistance', models.IntegerField()),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('oneHanded', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Leg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('level', models.IntegerField()),
                ('hpMax', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('physicalResistance', models.IntegerField()),
                ('magicalResistance', models.IntegerField()),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('oneHanded', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jon Doe', max_length=20)),
                ('level', models.IntegerField()),
                ('hpMax', models.IntegerField()),
                ('hp', models.IntegerField()),
                ('armor', models.IntegerField()),
                ('agility', models.IntegerField()),
                ('physicalResistance', models.IntegerField()),
                ('magicalResistance', models.IntegerField()),
                ('requiredLevel', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('oneHanded', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
