# Generated by Django 3.0.1 on 2019-12-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='chest',
            name='name',
            field=models.CharField(default='New Item', max_length=20),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(default='New Item', max_length=20),
        ),
        migrations.AlterField(
            model_name='head',
            name='name',
            field=models.CharField(default='New Item', max_length=20),
        ),
        migrations.AlterField(
            model_name='leg',
            name='name',
            field=models.CharField(default='New Item', max_length=20),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='New Item', max_length=20),
        ),
        migrations.AddField(
            model_name='character',
            name='characterClass',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='characterClass', to='app.CharacterClass'),
            preserve_default=False,
        ),
    ]
