# Generated by Django 3.0.1 on 2019-12-20 13:05

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191220_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chest',
            name='level',
        ),
        migrations.RemoveField(
            model_name='chest',
            name='oneHanded',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='hpMax',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='level',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='magicalResistance',
        ),
        migrations.RemoveField(
            model_name='consumable',
            name='physicalResistance',
        ),
        migrations.RemoveField(
            model_name='head',
            name='level',
        ),
        migrations.RemoveField(
            model_name='head',
            name='oneHanded',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='level',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='oneHanded',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='level',
        ),
        migrations.AddField(
            model_name='chest',
            name='characterClasses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chestCharacterClass', to='app.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='head',
            name='characterClasses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='headCharacterClass', to='app.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='leg',
            name='characterClasses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='legCharacterClass', to='app.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weapon',
            name='characterClasses',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='weaponCharacterClass', to='app.CharacterClass'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='character',
            name='level',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chest',
            name='agility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chest',
            name='armor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chest',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='chest',
            name='hpMax',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chest',
            name='magicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='chest',
            name='physicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='agility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='armor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='head',
            name='agility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='head',
            name='armor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='head',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='head',
            name='hpMax',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='head',
            name='magicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='head',
            name='physicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='agility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='armor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='hpMax',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='magicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='leg',
            name='physicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='agility',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='armor',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='hp',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='hpMax',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='magicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='physicalResistance',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
