# Generated by Django 3.0.1 on 2020-01-06 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200106_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='chest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chestInventory', to='app.Chest'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='headInventory', to='app.Head'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='legInventory', to='app.Leg'),
        ),
    ]
