# Generated by Django 3.0.1 on 2019-12-20 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20191220_1453'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chest',
            old_name='characterClasses',
            new_name='characterClass',
        ),
        migrations.RenameField(
            model_name='head',
            old_name='characterClasses',
            new_name='characterClass',
        ),
        migrations.RenameField(
            model_name='leg',
            old_name='characterClasses',
            new_name='characterClass',
        ),
        migrations.RenameField(
            model_name='weapon',
            old_name='characterClasses',
            new_name='characterClass',
        ),
    ]
