# Generated by Django 3.0.1 on 2019-12-20 14:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191220_1501'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chestInventory', to='app.Chest')),
            ],
        ),
        migrations.CreateModel(
            name='InventoryConsumable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('consumable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Consumable')),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Inventory')),
            ],
        ),
        migrations.AddField(
            model_name='inventory',
            name='consumables',
            field=models.ManyToManyField(through='app.InventoryConsumable', to='app.Consumable'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='head',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headInventory', to='app.Head'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='leg',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='legInventory', to='app.Leg'),
        ),
    ]
