# Generated by Django 3.0.1 on 2019-12-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191220_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chest',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='head',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='leg',
            name='hp',
        ),
        migrations.RemoveField(
            model_name='weapon',
            name='hp',
        ),
        migrations.AlterField(
            model_name='chest',
            name='name',
            field=models.CharField(default='New Item', max_length=40),
        ),
        migrations.AlterField(
            model_name='consumable',
            name='name',
            field=models.CharField(default='New Item', max_length=40),
        ),
        migrations.AlterField(
            model_name='head',
            name='name',
            field=models.CharField(default='New Item', max_length=40),
        ),
        migrations.AlterField(
            model_name='leg',
            name='name',
            field=models.CharField(default='New Item', max_length=40),
        ),
        migrations.AlterField(
            model_name='weapon',
            name='name',
            field=models.CharField(default='New Item', max_length=40),
        ),
    ]
