# Generated by Django 3.0.1 on 2019-12-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191220_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='inventory',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.Inventory'),
            preserve_default=False,
        ),
    ]
