# Generated by Django 3.0.2 on 2020-01-08 09:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20191227_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='un sbire de Alain', max_length=20)),
                ('hpMax', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('hp', models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('strength', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('agility', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('intelligence', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)])),
                ('physical_resistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('magical_resistance', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
